### ISSUE TITLE
[BUG]Pagination 총 페이지수 계산 잘못됨

### ISSUE THREAD

**Issue by bebusl** [algorithmQNA/algorithmQNA_frontend#17]
https://github.com/algorithmQNA/algorithmQNA_frontend/blob/5d5a52ab9f94c512bf34a72d17728ba3778b1276/src/components/Pagination/Pagination.tsx#L28

총 데이터 개수 37개이고 한 페이지당 표시되는 개수가 20개일 때 2페이지까지 보여야 정상인데
(총 데이터 개수 / 한 페이지당 표시 개수)값을 **내림**해버려서 1페이지만 보여지는 현상이 발생하고 있습니다.

Math.floor -> Math.ceil로 변경해야 할 것 같습니다.

**Comment by jeonoseung** [comment]
수정 했습니다~
