### ISSUE TITLE
[Fix] 좋아요 상태 분리

### ISSUE THREAD

**Issue by bebusl** [algorithmQNA/algorithmQNA_frontend#24]
https://github.com/algorithmQNA/algorithmQNA_frontend/blob/c1e1abf71689cebe3d42f6f628c2a6de65eb48ba/src/components/Board/PostView/PostContent.tsx#L37

* 좋아요는 boolean, null 즉 true, false, null이렇게 세가지의 값을 갖게 됩니다.
* 현재는 null에 대한 처리가 되어있지 않은 상태라서 null처리도 해주어야 할 것 같습니다.

**Comment by jeonoseung** [comment]
isLiked의 값에 따라 undefined로 값을 넘겨주게 변경했습니다.
그리고 수정 하다보니 cancel값을 넘겨줄 때 반대로 넘겨주는거 같아서 같이 수정했습니다
 다음 PR 할 때 같이 올리겠습니다
![image](https://github.com/algorithmQNA/algorithmQNA_frontend/assets/114666481/0c393bcc-b884-4754-a7c7-d278cc7fd39b)
