### ISSUE TITLE
Image upload Failed in editor

### ISSUE THREAD

**Issue by so1omon** [algorithmQNA/algorithmQNA_frontend#26]
버킷에 업로드까지는 잘 되는데, 알 수 없는 이유로 alert가 실행되고 글에 내용이 반영되지 않습니다.

![image](https://github.com/algorithmQNA/algorithmQNA_frontend/assets/37677461/013ea7f0-6613-4acd-8dcb-10397004b67c)

![image](https://github.com/algorithmQNA/algorithmQNA_frontend/assets/37677461/b063c6e8-7475-4376-8281-e7b92448f0e7)

**Comment by jeonoseung** [comment]
현재 작업중인 브랜치에서 수정했고 다음 merge할 때 같이 올리겠습니다
