### ISSUE TITLE
각 팀원별 역할 → 각 포지션별로 (각자 알아서 적기)

### ISSUE THREAD

**Issue by bebusl** [algorithmQNA/algorithmQNA_frontend#46]
그냥 단순하게 리스트형태로 작성해주시면 됩니다.

**Comment by bebusl** [comment]
@bebusl 
* 공용 컴포넌트 제작
* 마이페이지 제작
* 관리자 게시판 제작
* 대댓글 및 하이라이팅 기능 구현
* 페이지별 권한 설정
* 개발/배포 서버 설정

**Comment by jeonoseung** [comment]
@jeonoseung 
- 셀렉트 박스 컴포넌트 제작
- 대시보드 페이지 제작
- 게시물 타입별 조회 페이지 제작 (Q&A,TIP)
- 알람 조회(헤더) 컴포넌트 제작
