### ISSUE TITLE
프로젝트 진행하면서 어려웠던 부분, 새로 배웠던 부분, 추후 개선사항

### ISSUE THREAD

**Issue by bebusl** [algorithmQNA/algorithmQNA_frontend#47]
작성 템플릿

//1번부터 시작하시면 됩니다.
### [번호]. 내용 요약해서 제목으로
어려웠던 부분 -> 어떤 부분이 어려웠고 어떤 방식으로 해결했는지 정리
배운부분 -> 그냥 배운 부분 정리
추후 개선사항 -> 어떤 부분이 아쉽고 어떤 방향으로 개선할 지 정리

! 본문은 한 항목당 5~10줄 내외로 작성하시면 될 것 같습니다.

**Comment by bebusl** [comment]
@bebusl 
### 1. [어려웠던 부분] 대댓글 react-query caching(하이라이트 기능, 대댓글)
개인적으로 이번 프로젝트에서 중요하게 생각했던 점 중 하나는 '리액트 쿼리의 캐싱을 적절하게 잘 사용해서 api 요청 횟수를 최대한 줄이기!'였습니다.  기본적인 게시글 CRUD에 대해서 캐싱 적용을 하기는 쉬웠으나, 댓글 부분에서 조금 막혔던 것 같습니다. 'ALGO싶다'에서는 최대 깊이 3까지 대댓글을 달 수 있고, 대댓글도 채택을 할 수 있는 구조입니다. 기본적으로 깊이 0,1의 댓글은 열려있는 상태로 사용자에게 노출되지만 깊이 3의 대댓글같은 경우 처음에는 사용자에게 노출되지 않습니다. 
만약 사용자가 채택 답변을 보기/댓글 관련 알람 확인하기 버튼을 눌렀을 때 해당하는 댓글을 하이라이팅하게 되는데 하이라이팅 할 댓글이 깊이가 3이라면 root댓글-부모댓글-하이라이팅 댓글이 중첩된 배열 형태로 담겨져 옵니다. 처음엔 하이라이팅용 페이지를 따로 구현하는 게 가장 쉽지 않을까 했는데 그러면 그냥 일반 페이지를 갔을 때 하이라이팅 시 불러온 댓글 정보를 다시 불러와서 불필요한 api 호출이 발생하는 문제가 있었습니다. 그래서 navigate할 때 state를 담아 보내고 state에 값이 있을 때 하이라이트 api를 요청하고 하이라이팅 댓글이 있는 페이지의 캐시에 저장해 불필요한 api호출이 없도록 하였습니다.(이미지 포함해야할 듯)

### 2. [배운부분] recoil로 공용 모달 사용하기
신고된 게시글/댓글 모달의 경우 여러 신고 내역이 있고 신고 내역을 클릭했을 때 모달에서 상세 신고내역을 보여주는 형식입니다. 처음에는 각 신고 내역 컴포넌트에 모달 상태를 제어할 수 있는 코드를 삽입했지만, 페이지 당 하나의 모달을 두고 내용만 갈아끼워주는 게 낫겠다는 판단이 들었습니다. 그래서 recoil을 이용해 신고된 게시글/댓글 모달을 다룰 atom을 각각 하나씩 만들어 사용했습니다. 이렇게 atom을 각각 만들어 사용하다 보니 atom의 내용물은 같은데 다른 이름으로 관리하는 게 조금 어색해 보였습니다. 그래서 atomFamily를 이용해 같은 이름으로 관리할 수 있게 하였습니다. atomFamily를 사용함으로써 Modal을 다루는 atom이라는 것을 이름으로 한 눈에 쉽게 파악할 수 있었고, 다른 모달을 다루는 상황에서도 사용할 수 있게 확장성이 높아졌습니다.

### 3. 추후 개선사항 - 리팩토링, 최적화
컴포넌트를 나름대로 분리한다고 해두었지만 댓글뷰같이 기능이 많이 들어가는 부분에 대해서는 잘 분리가 되지 않은 점이 많이 아쉽습니다.
일반 사용자의 경우 관리자 게시판을 볼 일이 없지만 현재는 빌드할 때 한꺼번에 묶여서 빌드되기 때문에 초기로딩 시 모든 코드를 읽어들이게됩니다. 초기 로딩할 js파일의 크기가 커지므로 초기 로딩 속도가 느려질 수 있습니다. 그래서 관리자 게시판이나 마이페이지같이 비교적 나중에 접근하게 될 가능성이 있는 페이지들은 lazy로딩을 하여 초기 로딩할 Js파일의 사이즈를 줄여 제공하면 좋을 것 같습니다.

**Comment by jeonoseung** [comment]
@jeonoseung 

### 1. [어려웠던 부분] 협업
처음 개인 프로젝트를 하고 나서 자신감을 얻어 팀 프로젝트를 참여하게 됐지만 협업이 생각 외로 많이 어려웠습니다.
개인 프로젝트 할 때는 전부 본인이 하기 때문에 따로 정리를 하지 않았지만 팀 프로젝트에서는 다른 사람과 같이 진행하기 위해서 체계적으로 움직여야 하기 때문에 이를 처음 접하는 저에겐 많이 어려운 부분이었습니다. 
UI를 디자인하기 위해 사용한 figma, 일정, 기능 정리를 위해 사용한 notion 같은 부분은 사용 자체는 어렵지 않았으나 다른 사람에게 보여줘야 하기 때문에 어떻게 하면 보기 쉽게 표현할까 생각이 많이 필요해서 어려웠던 것 같습니다.
### 2. [어려웠던 부분] 구글 로그인
아예 처음 해보는 것은 아니었나 구글 로그인 방식에도 여러 방식이 있었고 이를 알기 전에는 단순히 나오는 대로 구현을 했습니다. 구현 후 문제가 됐고 다시 팀에서 정한 방식으로 구현을 했었습니다. 구현을 했고 배포 서버를 통하여 구글 로그인을 시도 했지만 또 문제가 생겼습니다. 프론트에서 혼자 주고 받을 때 문제 없던 코드가 백엔드 배포 서버와 주고 받을 때는 문제가 생겼습니다. 물론 배포 서버에 맞춰 이를 변경했지만 해결하지 못했습니다. 팀원의 도움을 받아 결과적으론 해결했으나 구글 로그인에 대한 부분을 자세히 알아봐야 했기 때문에 많이 어려웠던 것 같습니다.
