### ISSUE TITLE
글쓰기 페이지 초기화 안됨

### ISSUE THREAD

**Issue by bebusl** [algorithmQNA/algorithmQNA_frontend#48]
* 글쓰기 완성하고 나서 다시 글 작성하러 들어가면 이전에 작성한 내용이 그대로 남아있습니다.

## 재현방법
1. 글 작성 - 글 작성완료
2. 대시보드로 이동
3. 다시 작성페이지로 감

**Comment by jeonoseung** [comment]
수정 완료 했습니다.
알람 확인, 삭제 기능 추가할 때 같이 올리겠습니다
