### ISSUE TITLE
인증정보 없이 초기 페이지 접근 시 "사용자 인증 실패" alert창이 무한반복으로 뜸

### ISSUE THREAD

**Issue by so1omon** [algorithmQNA/algorithmQNA_frontend#52]
![image](https://github.com/algorithmQNA/algorithmQNA_frontend/assets/37677461/31bfc5e8-740e-409b-a897-0f8b78543b49)

백단 문제인지 프론트단 문제인지 정확히 테스트는 해봐야겠지만, API 서버 인증과정에 문제가 있어 보이지는 않습니다.

**Comment by bebusl** [comment]
api 호출하고 오류가 발생하면 무조건 alert를 뜨게 해놔서 발생하는 문제입니다! 수정해서 반영해두도록 하겠습니다.
