### ISSUE TITLE
공지사항 작성 후 작성한 게시글이 목록에서 조회되지 않음

### ISSUE THREAD

**Issue by so1omon** [algorithmQNA/algorithmQNA_frontend#56]
* 공지사항 등록 전
![image](https://github.com/algorithmQNA/algorithmQNA_frontend/assets/37677461/99c28a3d-ff36-43ac-973d-cb8748f047c5)
* 공지사항 등록 직후 넘어가는 페이지
![image](https://github.com/algorithmQNA/algorithmQNA_frontend/assets/37677461/4d3f60f1-2ec9-4e97-add2-37b488970fa3)
* PAGE RELOAD
![image](https://github.com/algorithmQNA/algorithmQNA_frontend/assets/37677461/1a8dda72-d859-4ce6-9343-12e053e50cb6)

공지사항 작성 후 공지사항 목록을 보면 작성한 게시글이 보이지 않고, reload를 해야만 보이는 현상이 발생합니다.

이번에 해결된 로그인 관련 이슈에서도 예전에 언급된 비슷한 내용인데, 비단 공지사항 목록 뿐만 아니라 일반 게시글 작성 시에도 비슷한 상황이 발생하는 것 같습니다.

**Comment by bebusl** [comment]
전체적으로 캐싱 기간을 수정하도록 하겠습니다!
